"""finnhub

Revision ID: 20c11f12f527
Revises: 6bf3de3db89c
Create Date: 2026-01-26 10:48:06.328254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c11f12f527'
down_revision: Union[str, Sequence[str], None] = '6bf3de3db89c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dividends', sa.Column('latest_price', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('dividends', sa.Column('yield_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('dividends', sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True))
    op.alter_column('dividends', 'dividend_ex_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('dividends', 'record_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('dividends', 'payment_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('dividends', 'dividend_rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=True)
    op.alter_column('dividends', 'indicated_annual_dividend',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=True)
    op.alter_column('dividends', 'announcement_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dividends', 'announcement_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('dividends', 'indicated_annual_dividend',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=False)
    op.alter_column('dividends', 'dividend_rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=False)
    op.alter_column('dividends', 'payment_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('dividends', 'record_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('dividends', 'dividend_ex_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('dividends', 'market_cap')
    op.drop_column('dividends', 'yield_percent')
    op.drop_column('dividends', 'latest_price')
    # ### end Alembic commands ###
