"""create inv tables

Revision ID: 6bf3de3db89c
Revises: b409d16bdb31
Create Date: 2026-01-25 20:58:16.295088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf3de3db89c'
down_revision: Union[str, Sequence[str], None] = 'b409d16bdb31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_dividends_symbol_exdate', 'dividends', ['symbol', 'dividend_ex_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dividends_symbol_exdate', table_name='dividends')
    # ### end Alembic commands ###
