"""vector

Revision ID: 96e0cfd84636
Revises: b5ddfe309bb3
Create Date: 2026-01-29 21:11:23.792504

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import Vector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e0cfd84636'
down_revision: Union[str, Sequence[str], None] = 'b5ddfe309bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dividend_chunks', 'embedding',
               existing_type=Vector(dim=384),
               type_=Vector(dim=1536),
               existing_nullable=True)
    op.drop_index(op.f('ix_dividend_chunks_div_id'), table_name='dividend_chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dividend_chunks_div_id'), 'dividend_chunks', ['div_id'], unique=False)
    op.alter_column('dividend_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    # ### end Alembic commands ###
