"""create inv tables

Revision ID: b409d16bdb31
Revises: 
Create Date: 2026-01-25 20:44:24.384646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b409d16bdb31'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dividends',
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('dividend_ex_date', sa.Date(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('dividend_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('indicated_annual_dividend', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('announcement_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividends_company_name'), 'dividends', ['company_name'], unique=False)
    op.create_index(op.f('ix_dividends_dividend_ex_date'), 'dividends', ['dividend_ex_date'], unique=False)
    op.create_index(op.f('ix_dividends_id'), 'dividends', ['id'], unique=False)
    op.create_index(op.f('ix_dividends_note'), 'dividends', ['note'], unique=False)
    op.create_index(op.f('ix_dividends_symbol'), 'dividends', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dividends_symbol'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_note'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_id'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_dividend_ex_date'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_company_name'), table_name='dividends')
    op.drop_table('dividends')
    # ### end Alembic commands ###
