"""vector

Revision ID: b5ddfe309bb3
Revises: 20c11f12f527
Create Date: 2026-01-28 21:32:47.095838

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import Vector

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ddfe309bb3'
down_revision: Union[str, Sequence[str], None] = '20c11f12f527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dividend_chunks',
    sa.Column('div_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dividend_chunks_div_chunk', 'dividend_chunks', ['div_id', 'chunk_index'], unique=True)
    op.create_index(op.f('ix_dividend_chunks_div_id'), 'dividend_chunks', ['div_id'], unique=False)
    op.create_index(op.f('ix_dividend_chunks_id'), 'dividend_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_dividend_chunks_note'), 'dividend_chunks', ['note'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dividend_chunks_note'), table_name='dividend_chunks')
    op.drop_index(op.f('ix_dividend_chunks_id'), table_name='dividend_chunks')
    op.drop_index(op.f('ix_dividend_chunks_div_id'), table_name='dividend_chunks')
    op.drop_index('ix_dividend_chunks_div_chunk', table_name='dividend_chunks')
    op.drop_table('dividend_chunks')
    # ### end Alembic commands ###
